---
 homebrew_cask_packages:
  - alfred
  - dropbox
  - omnifocus
  - textexpander
  - nvalt
  - screenhero
  - iterm2
  #- intellij-idea
  - sublime-text3
  - rowanj-gitx
  - caffeine
  - google-chrome
  - firefox
  - skype
  - vlc
  - sizeup
  - transmission
  - java6
  - java7
