---
homebrew_install_path: /usr/local
homebrew_brew_bin_path: /usr/local/bin

homebrew_taps:
 - caskroom/cask
 - caskroom/versions
 - homebrew/versions
 - homebrew/binary

homebrew_packages:
 - { name: brew-cask }
 - { name: wget }
 # zsh
 - { name: zsh }
 - { name: zsh-completions }
 # Java
 - { name: jenv }
 # Ruby
 - { name: chruby }
 - { name: ruby-install }
 # projects
 - { name: heroku-toolbelt }
